### PR TITLE
Rename "quality-tools" directory

### PR DESCRIPTION
**Pull request by szepeviktor**
A second choice could be "qa-tools".

But "quality-tools" means something completely [diffferent](https://www.makitatools.com/products/tools/cordless/40v-xgt/saws/circular-saws).

### CODE REVIEW

**Comment by szepeviktor** [comment]
BTW If are deeply in QA 🌊 you can swim my ocean of the total of 23 jobs in these workflows.
https://github.com/szepeviktor/byte-level-care/tree/master/.github/workflows
The problems they prevent are all seen in the wild.

**Comment by ahegyes** [comment]
Hi @szepeviktor! Thank you for opening this PR! 

I was actually lacking inspiration when naming that folder, so I followed the naming "convention" used in PHPStorm: 

This folder structure is already deeply embedded in our organization's workflows, so we'll probably just stick with it for the time being. But thank you for the suggestion!

**Comment by szepeviktor** [comment]
All right - all right.
I see I cannot take those _quality tools_ from you.

I am deeply sorry. I would sent a PR to the authors of PHPStorm.

**Comment by szepeviktor** [comment]
Naming a concept is critical.
Using another name for a concept prevents you from thinking about it.

**Pull request closed without merging**
